name: Master

on:
  push:
    tags:
    - '*'

  workflow_dispatch:

# env:
#   ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
#   ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
#   ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
#   ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

jobs:
  terraform-step:
    uses: brandoneto/terraform-resume/.github/workflows/blank.yml@master
    secrets: inherit
  # desorty-step:
  #   uses: brandoneto/terraform-resume/.github/workflows/destory.yml@master
  # build:
  #   runs-on: ubuntu-latest
  #   steps:
