name: Master

on:
  push:
    tags:
    - '*'

  workflow_dispatch:



jobs:
  # terraform-step:
  #   uses: brandoneto/terraform-resume/.github/workflows/blank.yml@master
  #   secrets: inherit
  desorty-step:
    uses: brandoneto/terraform-resume/.github/workflows/destory.yml@master
    secrets: inherit
  # build:
  #   runs-on: ubuntu-latest
  #   steps:
